version: '3.8'
services:
  app:
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    command: npx nodemon --watch src --exec ts-node src/main.ts
    environment:
      NODE_ENV: development
