version: '3.8'

services:
  app:
    image: katyastan/nodejs2024q3-service-app:latest
    container_name: app
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - '4000:4000'
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    env_file: .env.postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  db-logs:
